### ISSUE TITLE
Rendering in Coercion Types subsection is broken

### ISSUE THREAD

**Issue by lukaramu** [rust-lang-nursery/reference#96]
In the section on type coercions, the [list of allowed coercions](https://doc.rust-lang.org/nightly/reference/type-coercions.html#coercion-types) looks quite wonky (on a recent version of Chrome):
<details>
<summary>Image</summary>

![chrome_2017-08-07_15-49-15](https://user-images.githubusercontent.com/3811822/29029505-2f0739e4-7b88-11e7-9f75-a3577c160d29.png)
</details>

For reference, the [rendering on GitHub itself](https://github.com/rust-lang-nursery/reference/blob/master/src/type-coercions.md#coercion-types) is fine.
I compared the generated HTML and for the first few items, it's identical (for the last few it's only syntax highlighting differences), so it seems like this is a CSS issue (with mdbook?).

**Comment by projektir** [comment]
The issue seems to arise when, for a given `<li>` element, there is no text in front of the `<code>` tag. Setting the `<p>` element to be `inline-block`, for example, seems to fix this for those individual cases, but is not favorable in the general case as it makes everything too tall. Perhaps user agent CSS or hljs CSS that tries to force `<p>` to be a block is causing this.  But this doesn't explain why this is happening in Chrome in particular.

This issue seems gone in the current version of Chrome Canary with the user agent CSS remaining the same, so perhaps this is a Chrome bug.

**Comment by Havvy** [comment]
So, if this goes away in Chrome's (next/current?) beta, then we can close this issue.

**Comment by alercah** [comment]
I do not see this issue in current Chrome.

**Comment by Havvy** [comment]
Transient Chrome rendering bug doesn't plague us anymore, so closing.
